spring:
  application:
    name: code-judge
  datasource:
    url: jdbc:mysql://switchback.proxy.rlwy.net:49925/railway
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 드라이버
    username: root
    password: RClsobdReFppPUFNEaMYCXjBanOBehpC
  jpa:
    hibernate:
      ddl-auto: update # 스키마 자동 업데이트 (필요에 따라 create, validate 등으로 변경 가능)
    show-sql: true # 실행되는 SQL 쿼리 출력
    properties:
      hibernate:
        "[format_sql]": true # SQL 포맷팅
        dialect: org.hibernate.dialect.MySQLDialect # MySQL에 맞는 Hibernate 방언 설정

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
